dist: bionic
language: python
sudo: required
services:
  - docker

matrix:
  include:
    - name: Plone 5.2 (Python 3.6)
      python: 3.6
      env:
        - python_version=3.6
        - PLONE_VERSION=52

    - name: Plone 5.2 (Python 3.7)
      python: 3.7
      env:
        - python_version=3.7
        - PLONE_VERSION=52

    - name: Plone 5.2 (Python 3.8)
      python: 3.8
      env:
        - python_version=3.8
        - PLONE_VERSION=52
      dist: bionic

  fast_finish: true

  allow_failures:
    - python: 3.8

env:
  global:
    - ES_VERSION=6.3.0
  matrix:
    - PLONE_VERSION=52  QA=true


cache:
  pip: true
  directories:
  - eggs
  - downloads

before_script:
  - sleep 10

before_install:
  - docker run -d -e "cluster.name=docker-cluster" -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" -p 9200:9200 docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION}
  - virtualenv -p `which python` .
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - bin/pip install -r requirements.txt -c constraints_plone$PLONE_VERSION.txt

install:
  - sed -ie "s#plone-x.x.x.cfg#test_plone$PLONE_VERSION.cfg#" travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg

script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
# Run code-analysis, except on Python 3.6, which mysteriously fails to find zc.buildout.
  - python --version 2> /dev/stdout | grep 3.6 || bin/code-analysis
  - bin/test --all

after_success:
  - bin/test-coverage
  - pip install coverage==4.5.4 coveralls
  - coveralls


notifications:
  email:
    - connect2nazrul@gmail.com
